var discrepancies = [
 {id:"0", counter:0, list:["pleasantly warm", "unbearably hot"]},
 {id:"1", counter:0, list:["an average", "a broken", "a close"]},
 {id:"2", counter:0, list:["a playful intelligent creature with emotions and memories and a unique personality whose throat had been slit with a knife", "a deliciously juicy hunk of meat roasted to a fatty crisp"]},
 {id:"3", counter:0, list:["a vegan monstrosity", "a surprisingly tasty recipe that had the wonderful bonus quality of not including ingredients that had been reaped by groping the teats of enslaved cattle"]},
 {id:"4", counter:0, list:["had been thickened with wheat, that most patriotic of grains", "had been thickened with wheat, tainting the sauce with gluten", "had been heated in the microwave, which could cause cancer", "had been heated in the microwave, which the scientific community had determined to be perfectly safe for human consumption", "among other ingredients contained a broth prepared with the flesh and bones of murdered chickens",]},
 {id:"5", counter:0, list:["that had been genetically modified, which would probably mutate the genes of whoever was idiotic enough to eat some", "that had been genetically modified, which was toxic", "that had been genetically modified, which was carcinogenic", "that had been genetically modified, which the scientific community had determined to be perfectly safe for human consumption", "fresh from the cob"]},
 {id:"6", counter:0, list:["whose natural sweetness had been spoiled with a topping of marshmallows", "that were probably infested with grubs thanks to being grown organic", "baked to perfection"]},
 {id:"7", counter:0, list:["A savory homemade apple stuffing", "Stuffing that had been ruined with too much salt"]},
 {id:"8", counter:0, list:["that among other ingredients contained city tap water, which by all known standards for testing was perfectly safe for human consumption", "that among other ingredients contained city tap water, which was probably contaminated with industrial waste", "that among other ingredients contained city tap water, which was probably polluted with runoff sewage", "that among other ingredients contained city tap water, which was laced with fluoride in a plot to control the minds of the populace", "zested with oranges"]},
 {id:"9", counter:0, list:["purple", "indigo", "lavender"]},
 {id:"10", counter:0, list:["had been created by god", "had been created by evolution", "maybe had been created by god through evolution", "were just algorithms in the simulation"]},
 {id:"11", counter:0, list:["incrementally to the global rise of carbon dioxide that was rapidly destroying", "nothing whatsoever to any rise in carbon dioxide that may have been naturally occurring in"]},
 {id:"12", counter:0, list:["Chemtrails", "Contrails"]},
 {id:"13", counter:0, list:["contaminating the air with experimental chemicals designed to tranquilize the population of the country", "poisoning the air with experimental chemicals designed to sterilize the population of the country", "signifying the release of horrifying amounts of carbon dioxide into the atmosphere", "the mark of an extraordinary feat of human engineering"]},
 {id:"14", counter:0, list:["ominously", "prettily", "radiantly"]},
 {id:"15", counter:0, list:["clunky", "reliable", "embarrassingly"]},
 {id:"16", counter:0, list:["sonic attack on", "bizarre ailments of", "mass hysteria of"]},
 {id:"17", counter:0, list:["emergency", "hoax", "hysteria", "situation"]},
 {id:"18", counter:0, list:["imaginary", "hypothetical", "treacherous"]},
 {id:"19", counter:0, list:["supposedly", "secretly"]},
 {id:"20", counter:0, list:["everybody loved", "nobody liked"]},
 {id:"21", counter:0, list:["on a juice cleanse", "detoxing", "attempting to purge imaginary toxins by fasting", "cosplaying as an anorexic"]},
 {id:"22", counter:0, list:["a shard of amethyst with a powerful healing energy", "which was literally just a rock", "which was just a shiny rock", "which the scientific community had determined to have no effect on human health whatsoever aside from the placebo benefits for gullible naturopaths", "which had probably been mined by enslaved children", "some occult talisman"]},
 {id:"23", counter:0, list:["despite that vaccines were known to contain formaldehyde and aluminum and mercury", "despite that vaccines were known to cause autism and epilepsy and diabetes", "a patriotic act to help protect fellow citizens from the possibility of untimely death", "which honestly wasn't that heroic considering that getting injected with a vaccine was approximately as risky as taking a couple of aspirin", "surely to the dismay of many a self-righteous conspiracy theorist"]},
 {id:"24", counter:0, list:["a precious symbol of the one true faith", "despite belonging to a religion whose sacred text explicitly forbid idols", "a superstitious amulet carved from wood", "which like any religious article was worthy of respect regardless of personal belief"]},
 {id:"25", counter:0, list:["a cigarette", "some smokeable cancer"]},
 {id:"26", counter:0, list:["despite that he refused to get vaccinated out of an alleged fear of poisoning his body", "a patriotic brand", "looking hip", "apparently suicidal"]},
 {id:"27", counter:0, list:["ghost", "wind"]},
 {id:"28", counter:0, list:["seemed like a terrible omen", "like all dreams was just a jumble of meaningless images generated by the synapses firing randomly in a brain", "like all dreams was a meaningful portrait of the most primary concerns in the current state of a psyche", "like all dreams was boring as fuck to have to sit there and listen to somebody ramble about", "like all dreams was a message projected into the collective subconscious of the human species by a race of shapeshifting reptilians with frighteningly superior technology"]},
 {id:"29", counter:0, list:["patriot", "traitor"]},
 {id:"30", counter:0, list:["hero", "fraud", "imbecile", "liar", "coward", "sellout", "clown", "maverick", "champion", "loser", "fascist"]},
 {id:"31", counter:0, list:["complaining about the investigation into foreign election interference", "protesting the witch hunt", "accusing nonpartisan officials of treason", "sending carefully coded messages about the cabal of cannibalistic pedophiles plotting against the country"]},
 {id:"32", counter:0, list:["disappointment", "sellout", "fraud", "liar", "trailblazer", "lionheart", "communist", "socialist", "fascist", "infidel", "hero"]},
 {id:"33", counter:0, list:["patriot", "traitor"]},
 {id:"34", counter:0, list:["only thanks to a forged birth certificate", "despite centuries of institutionalized racism", "in a moment&nbsp;of&nbsp;hope that&nbsp;now&nbsp;seemed&nbsp;so distant"]},
 {id:"35", counter:0, list:["terrorists", "alleged terrorists", "human scapegoats", "a bunch of&nbsp;ragheads"]},
 {id:"36", counter:0, list:["noble patriots", "brainwashed thugs", "state-sponsored murderers", "necessary monsters"]},
 {id:"37", counter:0, list:["tragic", "faked", "justified"]},
 {id:"38", counter:0, list:["plane", "holographic missile"]},
 {id:"39", counter:0, list:["Crisis&nbsp;actors", "Bystanders"]},
 {id:"40", counter:0, list:["the most horrific genocide in the history of the human species", "a fake genocide"]},
 {id:"41", counter:0, list:["a tragedy that could have been easily prevented if nobody owned guns", "a tragedy that could have been easily prevented if everybody owned guns", "yet another false flag attack that had been orchestrated by shapeshifting reptilians in a plot to control the world", "yet another vanload of body bags dumped at the morgue in an ongoing mental health crisis that the government was ignoring"]},
 {id:"42", counter:0, list:["the current day and the year", "dates that adhered to a false timeline distorted by phantom time"]},
 {id:"43", counter:0, list:["comforting", "frustrating", "maddening", "sad"]},
 {id:"44", counter:0, list:["caused cancer", "caused infertility", "had no effect whatsoever on human health"]},
 {id:"45", counter:0, list:["ugly", "beautiful", "elegant"]},
 {id:"46", counter:0, list:["compared to fossil fuels were a breathtakingly clean form of energy production", "still had a carbon footprint anyway"]},
 {id:"47", counter:0, list:["baffling", "infuriating", "shameful", "comforting"]},
 {id:"48", counter:0, list:["had no effect whatsoever on human health", "caused cancer", "caused infertility"]},
 {id:"49", counter:0, list:["still had a carbon footprint anyway", "compared to fossil fuels were a breathtakingly clean form of energy production"]},
 {id:"50", counter:0, list:["beautiful", "sleek", "ugly"]},
 {id:"51", counter:0, list:["a relief", "a disgrace", "a disaster"]},
 {id:"52", counter:0, list:["that nuclear power was so dangerous", "that nuclear power was so toxic", "that statistically nuclear power was both the safest and the cleanest form of energy production that the human species had ever invented", "how many jobs that would eliminate from the economy"]},
 {id:"53", counter:0, list:["were physically imperceptible", "seemed eerie", "seemed hazardous", "seemed scary", "were physically painful to the hypersensitive", "could cause infertility and dementia and autism and cancer", "the scientific community had determined to have no effect whatsoever on human health aside from the psychological maladies of paranoid technophobes"]},
 {id:"54", counter:0, list:["streaming", "buzzing", "humming", "swarming", "moving"]},
 {id:"55", counter:0, list:["wind", "ghost"]},
 {id:"56", counter:0, list:["brightly", "ominously", "prettily"]},
 {id:"57", counter:0, list:["protecting the country from terrorists", "spying indiscriminately on the populace of the country in a totalitarian scheme of mass surveillance", "transmitting&nbsp;intimate&nbsp;data about the&nbsp;populace of the&nbsp;country to enrich&nbsp;a mob&nbsp;of&nbsp;sociopathic corporations", "probably monitoring the weather"]},
 {id:"58", counter:0, list:["which meant now was a season of chaos", "which meant now was a season for reflection", "a purely visual phenomenon that would have no effect whatsoever on life for the human species aside from the superstitious impulses of delusional astrologers", "just another algorithm in the simulation"]},
 {id:"59", counter:0, list:["once", "never"]},
 {id:"60", counter:0, list:["round", "flat"]},
 {id:"61", counter:0, list:["the greatest country in the world", "the most prosperous country in the world", "the most diverse country in the world", "a country that while certainly both prosperous and diverse was statistically neither the most prosperous nor the most diverse in the world", "an evil empire whose riches had been amassed primarily by exploiting the natural resources of a land stolen from indigenous peoples and by manipulating and bullying and invading other nations and who incidentally claimed to be a champion of freedom and liberty and democracy and yet regularly supported homicidal dictators and terrorist militias when doing so would be strategically profitable", "a dystopian hellscape of dilapidated schools and homophobic billboards and trigger-happy cops and abortion-clinic bombings and televangelist fraudsters and criminally overpriced medicine and tax-dodging executives and kowtowing yuppies who were somehow deranged enough to believe that corporations deserved legal personhood", "a dystopian hellhole of radical universities and corrupt unions and welfare fraudsters and cop-killing gangbangers and drive-thru abortions and pornographic billboards and criminally expensive medicine and tree-hugging hippies who were somehow crazy enough to believe that chimpanzees deserved legal personhood", "a utopian paradise of equality and opportunity where every person was free to pursue any passion or dream or ambition regardless of religion or gender or ethnicity", "the birthplace of democracy", "the biggest contributor to climate change on the planet"]},
 {id:"62", counter:0, list:["global menace", "beacon of freedom", "profoundly flawed but nevertheless special republic"]},
 {id:"63", counter:0, list:["unbearably hot", "pleasantly warm"]},
 {id:"64", counter:0, list:["foreign", "peculiar", "suspicious", "desperate", "handsome"]},
 {id:"65", counter:0, list:["an orange", "a yellow", "a peach", "a saffron"]},
 {id:"66", counter:0, list:["hiking", "combat"]},
 {id:"67", counter:0, list:["an antifa", "a communist", "a socialist", "a fascist", "a terrorist", "a missionary", "a burglar", "a vlogger"]},
 {id:"68", counter:0, list:["wallet", "pistol", "revolver"]},
 {id:"69", counter:0, list:["hoarse", "gruff", "strange", "sexy"]},
 {id:"70", counter:0, list:["he had a rainbow aura", "like all human beings he did not emanate a visible aura"]},
 {id:"71", counter:0, list:["disoriented", "woozy", "stunned"]},
 {id:"72", counter:0, list:["deodorant", "cologne"]},
 {id:"73", counter:0, list:["bergamot", "sage", "patchouli"]},
 {id:"74", counter:0, list:["dramatically", "calmly"]},
 {id:"75", counter:0, list:["a grossly misleading statement considering that homeopathic practitioners were not actually medical doctors", "which was honestly still a shock", "providing some necessary context"]},
 {id:"76", counter:0, list:["had powerful healing properties in cases of trauma", "actually sounded interesting", "sounded delicious actually", "like all homeopathic remedies had no basis whatsoever scientifically"]},
 {id:"77", counter:0, list:["soothing", "creepy", "weird", "strangely erotic"]},
 {id:"78", counter:0, list:[",", "?"]},
 {id:"79", counter:0, list:["probably smart enough to realize that the well water out here might be contaminated with pesticides", "maybe not thirsty after all"]},
 {id:"80", counter:0, list:["had a concussion", "was on any drugs", "was on any medication", "liked football"]},
 {id:"81", counter:0, list:[",", "!"]},
 {id:"82", counter:0, list:["horror", "panic", "dread"]},
 {id:"83", counter:0, list:["melting rubber", "burning plastic"]},
 {id:"84", counter:0, list:["shock", "bewilderment", "alarm", "distress"]},
 {id:"85", counter:0, list:["vintage", "antique", "rusted&#8209;out"]},
 {id:"86", counter:0, list:["dazzling", "frightening", "sinister"]},
 {id:"87", counter:0, list:["honeyed", "candied", "marshmallowy", "liquory"]},
 {id:"88", counter:0, list:["wiper", "brake", "transmission"]},
 {id:"89", counter:0, list:["taillights", "brake&nbsp;lights"]},
 {id:"90", counter:0, list:["eight", "nine", "eleven", "ten"]},
 {id:"91", counter:0, list:["a blue", "a green", "a turquoise", "an aquamarine"]},
 {id:"92", counter:0, list:["bomber", "motorcycle"]},
 {id:"93", counter:0, list:["being a teacher", "becoming a poet", "building an airship", "inventing a pastry", "playing professional football", "discovering an enchanted sword", "riding a dolphin across the ocean", "intentionally crashing a drone into a flying saucer", "hacking the feds"]},
 {id:"94", counter:0, list:["might be", "was"]},
 {id:"95", counter:0, list:["gruesome", "painful", "grotesque", "unnatural"]},
 {id:"96", counter:0, list:["drenched", "glazed", "splattered"]},
 {id:"97", counter:0, list:["always fainted at the sight of blood", "sometimes fainted at the sight of blood", "was probably in a state of hypoglycemia after refusing to eat solid foods for a month"]},
 {id:"98", counter:0, list:["horrifying", "disgusting"]},
 {id:"99", counter:0, list:["everybody loved", "nobody liked"]},
 {id:"100", counter:0, list:["shrieked", "shouted"]},
 {id:"101", counter:0, list:["a surprisingly", "a fantastically", "an embarrassingly"]},
 {id:"102", counter:0, list:["frightened", "petrified", "frantic", "hopeless"]},
 {id:"103", counter:0, list:["her arm was broken", "her shoulder was dislocated"]},
 {id:"104", counter:0, list:["worried", "terrified"]},
 {id:"105", counter:0, list:["if", "when"]},
 {id:"106", counter:0, list:["might", "could", "would"]},
 {id:"107", counter:0, list:["awesome", "fearsome", "eldritch", "monstrous", "almost&nbsp;godlike"]},
 {id:"108", counter:0, list:["eerie", "frightening", "dreadful"]},
 {id:"109", counter:0, list:["horses stampeding through a nearby pasture", "tarot cards shuffling", "reels spinning in a slot machine", "prayer beads slipping from a table", "bullet casings dropping onto a floor", "a train clattering through a subway", "applause muffled by a window", "static over the airwaves", "a glitch in the simulation", "chocobos racing across a distant bridge"]},
 {id:"110", counter:0, list:["disbelief", "relief", "astonishment", "wonder"]},
 {id:"111", counter:0, list:["?", "!"]},
 {id:"112", counter:0, list:["Mom", "Gran", "Nana", "Rosie"]},
 {id:"113", counter:0, list:["gray", "brown", "maroon"]},
 {id:"114", counter:0, list:["sweatshirt", "sweater"]},
 {id:"115", counter:0, list:["opal", "pearl"]},
 {id:"116", counter:0, list:["pink", "red"]},
 {id:"117", counter:0, list:["had just eaten", "had just refused to eat", "was about to eat"]},
 {id:"118", counter:0, list:["turkey", "ham"]},
 {id:"119", counter:0, list:["twilight", "darkness"]},
 {id:"120", counter:0, list:["rain was drizzling", "sleet was falling", "snow was flurrying"]},
 {id:"121", counter:0, list:["pencil", "pen"]},
 {id:"122", counter:0, list:["tart", "noxious", "pleasant"]},
 {id:"123", counter:0, list:["was still lingering in", "had already&nbsp;faded from"]},
 {id:"124", counter:0, list:["pleasantly cool", "uncomfortably chilly", "absurdly cold"]},
 {id:"125", counter:0, list:["desperate", "determined"]},
 {id:"126", counter:0, list:["honor", "cherish"]},
 {id:"127", counter:0, list:["another day to pass without shutting down the illegal prison camp in the tropics", "another day to pass without building a wall at the border", "another day to pass without abolishing capital punishment", "another unborn baby to be murdered", "another innocent animal to be slaughtered", "another day to pass without defunding the police", "another day to pass without processing the monstrous backlog of untested rape kits", "the government to force parents to inject children with harmful vaccines", "marijuana to be legalized", "prostitution to be legalized", "another day to pass without creating a system of universal healthcare", "another day to pass without establishing a system for free college", "a communist takeover of the country", "a socialist takeover of the country", "a fascist takeover of the country", "an anarchist takeover of the country", "the country to become a godless pagan nation drunk on debauchery and vanity and sexual perversions", "the planet to be controlled by a cabal of cannibalistic pedophiles", "the planet to be controlled by a race of shapeshifting reptilians", "the planet to be destroyed by a generation of crybabies and narcissists too pampered and spineless to do whatever was necessary to ditch fossil fuels once and for all"]},
];

function shift(discrepancy) {
 document.getElementById(discrepancy.id).innerHTML = discrepancy.list[discrepancy.counter];
 if (discrepancy.counter < discrepancy.list.length - 1) {
  discrepancy.counter++;
 } else {
  discrepancy.counter = 0;
 }
}

discrepancies.forEach(shift);

setInterval(function(){discrepancies.forEach(shift);}, 1024);